---
- name: Run things as root on RHEV host
  vars:
    # Need to be root on the RHEV host
    ansible_ssh_user: root
  block:
  - name: Make sure user doesn't exist
    command: ovirt-aaa-jdbc-tool user delete {{ ocp4_workload_ama_rhev_vm_rhev_user_name }}
    ignore_errors: true

  - name: Add user
    command: >-
      ovirt-aaa-jdbc-tool user add {{ ocp4_workload_ama_rhev_vm_rhev_user_name }}
      --attribute=firstName={{ ocp4_workload_ama_rhev_vm_rhev_user_firstname }}
      --attribute=lastName={{ ocp4_workload_ama_rhev_vm_rhev_user_lastname }}

  - name: Get the current date and time
    setup:

  - name: Calculate end date
    set_fact:
      rhev_user_password_end_date: >-
        {{ '%Y-%m-%d %H:%M:%SZ' | strftime( ( ansible_date_time.epoch | int ) + ( 86400 * ocp4_workload_ama_rhev_vm_rhev_user_password_validity | int )  ) }}

  - name: Set up user password
    command: >-
      ovirt-aaa-jdbc-tool user password-reset {{ ocp4_workload_ama_rhev_vm_rhev_user_name }}
      --password=pass:{{ ocp4_workload_ama_rhev_vm_rhev_user_password }} --password-valid-to="{{ rhev_user_password_end_date }}"
