---
- name: Open firewall port 1521
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: 1521/tcp

- name: Install Oracle XE Preinstall RPMs
  dnf:
    state: present
    disable_gpg_check: true
    name:
    - https://yum.oracle.com/repo/OracleLinux/OL8/appstream/x86_64/getPackage/oracle-database-preinstall-21c-1.0-1.el8.x86_64.rpm

- name: Reboot the VM
  reboot:

- name: Install Oracle XE RPMs
  dnf:
    state: present
    disable_gpg_check: true
    name:
    - https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-21c-1.0-1.ol8.x86_64.rpm
  register: r_oracle_install

# Only configure Oracle on a first install
- name: Configure Oracle XE
  when: r_oracle_install.changed | bool
  block:
  - name: Copy database setup shell script to VM
    template:
      src: ./initial-configuration.j2
      dest: /root/initial-configuration
      owner: root
      group: root
      mode: 0770

  - name: Initial Oracle XE configuration
    command: /root/initial-configuration

  - name: Ensure database system service is enabled
    systemd:
      name: oracle-xe-21c
      enabled: true
      state: started
      daemon_reload: true

  - name: Set up oracle user
    blockinfile:
      dest: "/home/oracle/.bash_profile"
      create: true
      mode: 0664
      owner: oracle
      group: oinstall
      marker: "##### {mark} Oracle user configuration ######"
      content: |
        export ORACLE_HOME=/opt/oracle/product/21c/dbhomeXE
        export PATH=$PATH:$ORACLE_HOME/bin
        export ORACLE_SID=XE
        export ORAENV_ASK=NO
        . $ORACLE_HOME/bin/oraenv

  - name: Copy customer database setup SQL file to VM
    template:
      src: ./setup-customer-database.sql.j2
      dest: /home/oracle/setup-customer-database.sql
      owner: oracle
      group: oinstall
      mode: 0660

  - name: Copy customer database setup shell script file to VM
    template:
      src: ./setup-customer-database.j2
      dest: /home/oracle/setup-customer-database
      owner: oracle
      group: oinstall
      mode: 0775

  - name: Create customer database
    become_user: oracle
    command: /home/oracle/setup-customer-database

# https://www.golinuxcloud.com/run-script-at-startup-boot-without-cron-linux/#Step_31_Run_script_at_startup_with_systemd_after_network_becomes_reachable
# Add shell script to VM to change Hostname in configuration files
# upon reboot
# Edit /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
# -> Change HOST = 10.0.2.2 (or whatever the IP Address it)

# Edit /opt/oracle/homes/OraDBHome21cXE/network/admin/tnsnames.ora
# -> Change HOST twice to 10.0.2.2
# Modify Oracle service to start After the IP address update service
# Restart Oracle Service (only in playbook)
